dumper: try fix uploading issues

diff --git a/.github/workflows/rom_dumper.yml b/.github/workflows/rom_dumper.yml
--- a/.github/workflows/rom_dumper.yml
+++ b/.github/workflows/rom_dumper.yml
@@ -77,8 +77,7 @@ jobs:
         cd DumprX
         sudo chmod 777 *.sh
         bash setup.sh
-        pip3 install aospdtgen
-        pip3 install twrpdtgen
+        pip3 install aospdtgen twrpdtgen
 
     - name: Creating Dump
       run: |
@@ -90,8 +89,7 @@ jobs:
       run: |
         git config --global user.name "${{ env.UN }}"
         git config --global user.email "${{ env.UEM }}"
-        unset GITHUB_TOKEN
-        gh auth login --with-token <<< "${{ secrets.GTOKEN }}"
+        echo "${{ secrets.GTOKEN }}" gh auth login --with-token || { echo "Login failed!"; exit 1; }
 
     - name: Uploading ROM Dump
       run: |
@@ -173,15 +171,16 @@ jobs:
         max_size=48000000
         images=("recovery.img" "boot.img" "vendor_boot.img" "init_boot.img" "dtbo.img" "dtb.img")
         for pf in ${images[@]}; do
-           if [ -f $pf ]; then
-              if [[ $(stat -c %s $pf) -gt $max_size ]]; then
+           [ -f $pf ] && {
+              [[ $(stat -c %s $pf) -gt $max_size ]] && {
                  cp $pf /home/Auto-Dumper
                  gzip -f $pf
-              fi
-           fi
+              }
+           }
         done
         find /home/Auto-Dumper/DumprX/out -type f -size +50M -delete -exec echo "Deleted: "{} \;
         dat=$(date +%Y%m%d)
+        gh auth status &>/dev/null || { echo "${{ secrets.GTOKEN }}" gh auth login --with-token || { echo "Login failed!"; exit 1; }; }
         git init
         git branch -M dump-"$codename"-"$dat"
         git add .
@@ -238,6 +237,7 @@ jobs:
         cd vnd_project/android/vendor/"$brand"/"$codename"
         sudo chmod -R 777 *
         dat=$(date +%Y%m%d)
+        gh auth status &>/dev/null || { echo "${{ secrets.GTOKEN }}" gh auth login --with-token || { echo "Login failed!"; exit 1; }; }
         git init
         git branch -M vendor-"$codename"-"$dat"
         git add .
@@ -255,6 +255,7 @@ jobs:
         cd /home/Auto-Dumper
         codename=$(cat codename.txt)
         brand=$(cat brand.txt)
+        gh auth status &>/dev/null || { echo "${{ secrets.GTOKEN }}" gh auth login --with-token || { echo "Login failed!"; exit 1; }; }
         cd lineage-device-tree
         dat=$(date +%Y%m%d)
         git init
@@ -275,6 +276,7 @@ jobs:
         cd twrp-device-tree/$brand/$codename
         dat=$(date +%Y%m%d)
         [ ! -f BoardConfig.mk ] && cd "$brand"/"$codename"
+        gh auth status &>/dev/null || { echo "${{ secrets.GTOKEN }}" gh auth login --with-token || { echo "Login failed!"; exit 1; }; }
         git init
         git branch -M twrp-"$version"-"$dat"
         git add .
